### ISSUE TITLE
AttributeError bei Aufruf von ManagementNode.reset_instance_count in den Tests

### ISSUE THREAD

**Issue by Tomstaib** [Tomstaib/SEP_DMPG#3]
Beim Ausführen der Unit-Tests für die Klasse CompositeTree in Verteilung tritt ein Fehler auf, da die Methode reset_instance_count in der Klasse ManagementNode nicht vorhanden ist. Dieser Fehler führt dazu, dass mehrere Tests fehlschlagen, die diese Methode aufrufen. @MarStroe @Gittho793

**Comment by IlhanIngenc** [comment]
Liegt vermutlich an der falschen Simulation.py & dem damit fehlenden "src"-Verzeichnis.

**Comment by IlhanIngenc** [comment]
Das läuft nun, mit der richtigen Version von der simulations.py ;)
